chore(set-up-react-app)-181414707
atlp-rwanda/code-ninjas-fe pull request #1
Opened 2022-05-11 20:44 UTC by Robertishimwe

### 1. Name of task
Setup an empty react project
### 2. Pivot Tracker ID
[181414707](https://www.pivotaltracker.com/story/show/181414707)
### 3. Branch Name
ch-set-up-react-app-181414707
### 4. Description of task
should create a react project from scratch using Webpack 4, Babel, and the Airbnb linting option.

2022-05-12 17:58 UTC, itisWasp requested changes
Improve the commit message and make it descriptive.

2022-05-12 19:02 UTC, ericus123 requested changes

2022-05-12 19:02 UTC, ericus123 commented on .vscode/settings.json
> +}
remove this

2022-05-12 19:50 UTC, Robertishimwe commented on .vscode/settings.json
> +}
done

2022-05-12 19:51 UTC, Robertishimwe commented
> Improve the commit message and make it descriptive.

done

2022-05-13 06:21 UTC, itisWasp approved these changes

2022-05-13 12:06 UTC, Robertishimwe commented
@ericus123 is there any other thing remaining for this task?

2022-05-13 12:16 UTC, ericus123 approved these changes

2022-05-13 12:28 UTC, merged