Ft registration 181414716
atlp-rwanda/code-ninjas-fe pull request #10
Opened 2022-05-20 09:28 UTC by Robertishimwe

2022-05-21 09:17 UTC, Steve-Ndicunguye approved these changes, later dismissed

2022-05-22 12:31 UTC, itisWasp approved these changes, later dismissed

2022-05-22 18:27 UTC, ericus123 requested changes

2022-05-22 18:27 UTC, ericus123 commented on src/components/registration/formInPuts.jsx
> +// export default FormInPuts;
what's the use of this???

2022-05-23 04:47 UTC, Robertishimwe commented on src/components/registration/formInPuts.jsx
> +// export default FormInPuts;
resolved

2022-05-24 12:08 UTC, ericus123 requested changes

2022-05-24 12:08 UTC, ericus123 commented on src/styles/verify.scss
> +    background-color: #1d97a7;
colors can't be hardcoded as well

2022-05-25 07:06 UTC, ericus123 requested changes

2022-05-25 07:06 UTC, ericus123 commented on src/components/login/google.jsx
> +export default Google;
@Robertishimwe  what's the use of this component?

2022-05-25 07:06 UTC, ericus123 commented on src/components/registration/registrationForm.jsx
> +              color: '#1d97a7',
colors should not be hardcoded

2022-05-25 07:06 UTC, ericus123 commented on src/components/registration/registrationForm.jsx
> +                backgroundColor: '#1d97a7',
colors should not be hardcoded.
fix this wherever you have them hardcoded

2022-05-25 07:06 UTC, ericus123 commented on src/styles/footer.scss
> +    // bottom: 0;
remove this if not being used

2022-05-25 07:06 UTC, ericus123 commented on src/styles/variable.scss
> +$text: Montserrat;
are we using this font anywhere? this font-family is not the one used on figma

2022-05-26 06:53 UTC, Robertishimwe commented on src/styles/variable.scss
> +$text: Montserrat;
it is the one we have
<img width="329" alt="mmme" src="https://user-images.githubusercontent.com/81079680/170434220-21787925-3e60-44e1-88ec-cd1c42437499.PNG">

2022-05-27 11:26 UTC, niyojuste reviewed
@Robertishimwe Can you add an option for users to view their passwords as they input it

2022-05-27 14:13 UTC, niyojuste approved these changes, later dismissed

2022-05-27 14:13 UTC, niyojuste commented on src/components/registration/registrationForm.jsx
> +            />
Nicely done! 
One small detail though, the logic is inverted. You can either start with:
- `Checkbox defaultChecked` in **FormControlLabel** with `type="text"` in **TextField** _or_
- `Checkbox` only in **FormControlLabel** with `type="password"` in **TextField**

2022-05-29 17:52 UTC, itisWasp submitted a review, later dismissed

2022-05-30 04:51 UTC, ericus123 approved these changes

2022-05-30 04:52 UTC, merged