#181414718 (Feature): login with email & password
atlp-rwanda/code-ninjas-fe pull request #12
Opened 2022-05-22 18:02 UTC by Robertishimwe

2022-05-24 12:10 UTC, ericus123 requested changes

2022-05-24 12:10 UTC, ericus123 commented on src/components/login/loginForm.jsx
> +// import validationsForm from '../../validation/registrationValidation';
remove this

2022-05-24 12:10 UTC, ericus123 commented on src/styles/footer.scss
> +    // bottom: 0;
remove this

2022-05-27 10:14 UTC, niyojuste reviewed
- Once the registration is available, you can maybe add a link to **sign up** in case the user doesn't have an account yet
- Also, can you add an option for users to view their password as they input it

2022-05-27 11:45 UTC, Robertishimwe commented
> * Once the registration is available, you can maybe add a link to **sign up** in case the user doesn't have an account yet
> * Also, can you add an option for users to view their password as they input it

2022-05-27 11:45 UTC, Procech20 approved these changes, later dismissed

2022-05-27 11:47 UTC, Robertishimwe commented
> > * Once the registration is available, you can maybe add a link to **sign up** in case the user doesn't have an account yet >i wii add this after rebasing from registration
> > * Also, can you add an option for users to view their password as they input it >Done

2022-05-27 14:15 UTC, niyojuste approved these changes, later dismissed

2022-05-27 14:15 UTC, niyojuste commented on src/components/login/loginForm.jsx
> +            />
Nicely done! 
One small detail though, the logic is inverted. You can either start with:
- `Checkbox defaultChecked` in **FormControlLabel** with `type="text"` in **TextField** _or_
- `Checkbox` only in **FormControlLabel** with `type="password"` in **TextField**

2022-05-30 06:42 UTC, itisWasp submitted a review, later dismissed

2022-05-30 07:03 UTC, Procech20 submitted a review, later dismissed

2022-05-30 08:22 UTC, ericus123 requested changes
@Robertishimwe  Work on these changes as well as make sure you are really testing.
You should test the form input fields validations too. **ex:** expect an error if a particular input field is not field or is invalid

2022-05-30 08:22 UTC, ericus123 commented on src/components/login/socialAuth.jsx
> +  // eslint-disable-next-line no-unused-expressions
why are you disabling this rule???

2022-05-30 08:45 UTC, ericus123 requested changes

2022-05-30 08:45 UTC, ericus123 commented on src/components/login/loginForm.jsx
> +      })
configure Axios globally. with some basic headers that are being used ex: token.

2022-05-30 08:45 UTC, ericus123 commented on src/redux/store.js
> +    REGISTER,
why have unnecessary indentation changes ??? 
Are you using prettier configuration as configured?

2022-06-01 05:59 UTC, ericus123 approved these changes

2022-06-01 05:59 UTC, ericus123 commented on src/components/login/loginForm.jsx
> +      .post('https://barefoot-nomad-v2.herokuapp.com/api/auth/login', {
why is this hardcoded ????

2022-06-01 05:59 UTC, ericus123 commented on src/components/login/loginForm.jsx
> +    window.open('https://barefoot.onrender.com/api/auth/google', '_blank');
this shouldn't be hardcoded

2022-06-01 05:59 UTC, ericus123 commented on src/components/login/loginForm.jsx
> +  // eslint-disable-next-line no-unused-expressions
don't disable eslint rules. remove this and wherever you are disabling eslint rules

2022-06-01 06:00 UTC, merged