181414721 (Feature): Implement request table
atlp-rwanda/code-ninjas-fe pull request #19
Opened 2022-06-01 21:13 UTC by Procech20

### What does this PR do?

Implement user request table

### Description of Task to be completed?
- Use material UI for components design
- Create user request table pages to display the user's trip request data.

### How should this be manually tested?

To test the changes manually:

* clone repo on your local machine
* switch to ``ft-request-table-181414721`` branch
* start the application with `yarn dev` command
* switch to the `/triprequest` endpoint.

### What to expect after running the commands:

When you switch to the page, you'll see the users trip request table

### Any background context you want to provide?

- N/A

### Useful links

N/A

### What are the relevant pivotal tracker stories?

* [181414721](https://www.pivotaltracker.com/story/show/181414721)

### Screenshots (if appropriate)

- N/A

### Questions:

- N/A

2022-06-02 07:35 UTC, itisWasp approved these changes, later dismissed

2022-06-07 07:53 UTC, ericus123 requested changes

2022-06-07 07:53 UTC, ericus123 commented on src/components/request/Table.jsx
> +/* eslint-disable no-unused-vars */
remove these

2022-06-08 08:23 UTC, Robertishimwe approved these changes

2022-06-08 11:02 UTC, ericus123 commented on src/pages/request.jsx
> +    <>
react fragment is unnecessary here since we have one child

2022-06-08 11:03 UTC, ericus123 approved these changes

2022-06-08 11:04 UTC, merged